---
  
  - name: "Check if ansible is able to connect to {{ host }}"
    vars:
      host: wmp
    hosts: "{{ host }}"
    tags:
      - debug
    tasks:
      - name: debug check connection 
        debug:
          msg: "you are connected to {{ host }}"
      - name: touch a file in {{ host }} to confirm you got in 
        file:
          path: "{{ ansible_env.HOME }}/foobar"
          state: touch


  - name: Update and Upgrade APK
    vars:
      host: wmp
    hosts: "{{ host }}"
    become: yes
    tags:
      - apk
    tasks:
      - name: Update APK
        apt:
          update_cache: yes

      - name: Upgrade APK
        apt:
          upgrade: dist

  - name: Increase file descriptor limit for processes
    vars:
      host: wmp
    hosts: "{{ host }}"
    become: yes
    tags:
      - file-descriptor-limit
    tasks:
      - name: Add line to sysctl.conf
        become: yes
        lineinfile:
          path: /etc/sysctl.conf
          line: fs.file-max=512000
        notify: Schedule_reboot
    handlers:
      - name: Schedule_reboot
        reboot:
          reboot_timeout: 300

  - name: Install Packages
    vars:
      host: wmp
      packages:
        - build-essential
        - libtool
        - autotools-dev
        - automake
        - pkg-config
        - libssl-dev
        - libevent-dev
        - bsdmainutils 
        - libboost-system-dev 
        - libboost-filesystem-dev 
        - libboost-chrono-dev 
        - libboost-program-options-dev 
        - libboost-test-dev 
        - libboost-thread-dev 
        - libminiupnpc-dev 
        - libzmq3-dev 
    hosts: "{{ host }}"
    become: yes
    tags:
      - packages
    tasks:
      - name: "Install packages on {{ host }}"
        apt:
          name: "{{ item }}"
          state: present
        loop: "{{ packages }}"
  
  - name: Clone Bitcoind
    vars:
      host: wmp
    hosts: "{{ host }}"
    tags:
      - clone
    tasks:
      - name: Clone Bitcoind Git Repo
        git:
          repo: https://github.com/bitcoin/bitcoin.git
          dest: "{{ ansible_env.HOME }}/bitcoin"
          version: v25.0 


  - name: Configure, Compile, Install bitcoind
    vars:
      host: wmp
      compile: false
      install: false
    hosts: "{{ host }}"
    tags:
      - compile-bitcoind
    tasks:
      - name: Run autogen.sh
        shell: ./autogen.sh
        args:
          chdir: "{{ ansible_env.HOME }}/bitcoin"
          executable: /bin/bash

      - name: Configure Bitcoind
        shell: |
          ./configure CXXFLAGS="--param ggc-min-expand=1 --param ggc-min-heapsize=32768" \
                      --enable-cxx \
                      --with-zmq \
                      --without-gui \
                      --disable-shared \
                      --with-pic \
                      --disable-tests \
                      --disable-bench \
                      --enable-upnp-default \
                      --disable-wallet
        args:
          chdir: "{{ ansible_env.HOME }}/bitcoin"
          executable: /bin/bash

      - name: Compile Bitcoind 
        shell: make -j "$(($(nproc)+1))"
        args:
          chdir: "{{ ansible_env.HOME }}/bitcoin"
          executable: /bin/bash
        when: compile

      - name: Install Bitcoind 
        become: yes
        tags:
          - install 
        shell: make install
        args:
          chdir: "{{ ansible_env.HOME }}/bitcoin"
          executable: /bin/bash
        when: install

  - name: Download auth script 
    vars:
      host: wmp
    hosts: "{{ host }}"
    tags:
      - auth-script
    tasks:
      - name: Download rpcauth.py
        get_url:
          url: https://raw.githubusercontent.com/bitcoin/bitcoin/master/share/rpcauth/rpcauth.py
          dest: "{{ ansible_env.HOME }}/rpcauth.py"

  - name: Setup Bitcoin config
    vars:
      host: wmp
      network: mainnet
      prune: 25000
    hosts: "{{ host }}"
    tags:
      - bitcoin-config
    tasks:
      - name: Make ~/.bitcoin directory
        file:
          path: "{{ ansible_env.HOME }}/.bitcoin/"
          state: directory
          mode: 0744

      - name: Create bitcoin.conf 
        template:
          src: ./bitcoin.conf.j2
          dest: "{{ ansible_env.HOME }}/.bitcoin/bitcoin.conf" 

  - name: Setup Bitcoin on systemd 
    vars:
      host: wmp
    hosts: "{{ host }}"
    become: yes
    tags:
      - systemd 
    tasks:
      - name: Copy over bitcoind.service 
        copy:
          src: ./bitcoind.service
          dest: /etc/systemd/system/bitcoind.service

      - name: Enable bitcoind service
        become: yes
        systemd:
          name: bitcoind
          enabled: yes





